# Generated by Django 5.2 on 2025-05-24 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_bio_userprofile_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-user__date_joined'], 'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Местоположение обновлено'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='offers_home_service',
            field=models.BooleanField(default=False, help_text='Предлагает ли барбер услуги с выездом на дом', verbose_name='Выезд на дом'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialization',
            field=models.JSONField(blank=True, default=list, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram',
            field=models.CharField(blank=True, help_text='Username в Telegram без @', max_length=50, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('client', 'Клиент'), ('barber', 'Барбер')], default='client', max_length=10, verbose_name='Тип пользователя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Номер WhatsApp для связи с клиентами', max_length=20, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='working_days',
            field=models.JSONField(blank=True, default=list, verbose_name='Рабочие дни'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='working_hours_from',
            field=models.TimeField(default='09:00', verbose_name='Начало работы'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='working_hours_to',
            field=models.TimeField(default='18:00', verbose_name='Конец работы'),
        ),
    ]
