# Generated by Django 5.2 on 2025-04-28 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='services/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration', models.IntegerField(default=30, help_text='Продолжительность в минутах')),
                ('type', models.CharField(max_length=50)),
                ('length', models.CharField(choices=[('short', 'Короткие'), ('medium', 'Средние'), ('long', 'Длинные')], max_length=20)),
                ('style', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
