# Generated by Django 5.2 on 2025-05-24 03:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_options_remove_service_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-views', '-created_at'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'ordering': ['order', '-uploaded_at'], 'verbose_name': 'Изображение услуги', 'verbose_name_plural': 'Изображения услуг'},
        ),
        migrations.AlterModelOptions(
            name='serviceview',
            options={'ordering': ['-viewed_at'], 'verbose_name': 'Просмотр услуги', 'verbose_name_plural': 'Просмотры услуг'},
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='service',
            name='barber',
            field=models.ForeignKey(limit_choices_to={'profile__user_type': 'barber'}, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Барбер'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(default=30, help_text='Продолжительность в минутах', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(240)], verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='service',
            name='length',
            field=models.CharField(choices=[('short', 'Короткие'), ('medium', 'Средние'), ('long', 'Длинные')], max_length=20, verbose_name='Длина волос'),
        ),
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='style',
            field=models.CharField(choices=[('business', 'Деловой'), ('casual', 'Повседневный'), ('trendy', 'Трендовый'), ('vintage', 'Винтажный'), ('modern', 'Современный')], max_length=50, verbose_name='Стиль'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('classic', 'Классическая'), ('fade', 'Фейд'), ('undercut', 'Андеркат'), ('crop', 'Кроп'), ('pompadour', 'Помпадур'), ('textured', 'Текстурная')], max_length=50, verbose_name='Тип стрижки'),
        ),
        migrations.AlterField(
            model_name='service',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to='services/%Y/%m/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='serviceview',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_views', to='services.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='serviceview',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Ключ сессии'),
        ),
        migrations.AlterField(
            model_name='serviceview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='serviceview',
            name='viewed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра'),
        ),
        migrations.AlterField(
            model_name='serviceview',
            name='viewer_ip',
            field=models.GenericIPAddressField(verbose_name='IP адрес'),
        ),
    ]
