# Generated by Django 5.2 on 2025-05-25 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
    ]
