# Generated by Django 5.2 on 2025-05-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_banner_subtitle_remove_banner_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.AddField(
            model_name='banner',
            name='desktop_image',
            field=models.ImageField(default=1, upload_to='banners/desktop/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(default=1, upload_to='banners/mobile/'),
            preserve_default=False,
        ),
    ]
