# Generated by Django 5.2 on 2025-05-28 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_telegramaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramAccount',
        ),
    ]
